server:
  port: 9005
spring:
  application:
    name: tensquare-gathering
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_gathering?&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false

